// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-PBI8qoMmn_IS61hyf3NtiDR52x-YS7I',
    appId: '1:28743262873:web:657c7ca263965d09348e08',
    messagingSenderId: '28743262873',
    projectId: 'university-pal',
    authDomain: 'university-pal.firebaseapp.com',
    databaseURL: 'https://university-pal-default-rtdb.firebaseio.com',
    storageBucket: 'university-pal.appspot.com',
    measurementId: 'G-88F4N13BM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_7SdVBpaSrJprw8OmDkfv0lTuR2ZeX4Q',
    appId: '1:28743262873:android:5cbc71cd2aeb9a34348e08',
    messagingSenderId: '28743262873',
    projectId: 'university-pal',
    databaseURL: 'https://university-pal-default-rtdb.firebaseio.com',
    storageBucket: 'university-pal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOb8GNYu5I7dh_7FX-VX7WxVoVzN795wA',
    appId: '1:28743262873:ios:2e60a0377fb4523b348e08',
    messagingSenderId: '28743262873',
    projectId: 'university-pal',
    databaseURL: 'https://university-pal-default-rtdb.firebaseio.com',
    storageBucket: 'university-pal.appspot.com',
    iosClientId: '28743262873-v3138lnevttt3jafespmrotfjnm3re31.apps.googleusercontent.com',
    iosBundleId: 'com.example.messaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOb8GNYu5I7dh_7FX-VX7WxVoVzN795wA',
    appId: '1:28743262873:ios:2e60a0377fb4523b348e08',
    messagingSenderId: '28743262873',
    projectId: 'university-pal',
    databaseURL: 'https://university-pal-default-rtdb.firebaseio.com',
    storageBucket: 'university-pal.appspot.com',
    iosClientId: '28743262873-v3138lnevttt3jafespmrotfjnm3re31.apps.googleusercontent.com',
    iosBundleId: 'com.example.messaging',
  );
}
